export const blogPosts = [
    {
        title: "Blog Post 1",
        body: "Voluptas voluptatum tempora voluptas. Blanditiis ut accusantium qui nam. Quas omnis reprehenderit quasi est. Distinctio commodi qui sit dolore modi maxime.Sequi sunt illo fugit ea facilis voluptas ea fugit. Nesciunt voluptatem magnam cupiditate exercitationem ipsum praesentium non non. Sunt ullam voluptas et praesentium rem. Non id molestiae suscipit. Sunt voluptatum laboriosam quis et. Doloremque aliquid iusto cupiditate quo qui.",
        date: "Saturday, 26 February, 2020",
        views: 52,
        id: 1,
        author: "Kali Junior Brown",
        readTime: 30,
        upVotes: 0,
        downVotes: 0,
    },
    {
        title: "Blog Post 2",
        body: "Voluptas voluptatum tempora voluptas. Blanditiis ut accusantium qui nam. Quas omnis reprehenderit quasi est. Distinctio commodi qui sit dolore modi maxime.Sequi sunt illo fugit ea facilis voluptas ea fugit. Nesciunt voluptatem magnam cupiditate exercitationem ipsum praesentium non non. Sunt ullam voluptas et praesentium rem. Non id molestiae suscipit. Sunt voluptatum laboriosam quis et. Doloremque aliquid iusto cupiditate quo qui.",
        date: "Monday, 12 January, 2020",
        views: 76,
        id: 2,
        author: "Kali Junior Brown",
        readTime: 30,
        upVotes: 0,
        downVotes: 0,
    },
    {
        title: "Blog Post 3",
        body: "Voluptas voluptatum tempora voluptas. Blanditiis ut accusantium qui nam. Quas omnis reprehenderit quasi est. Distinctio commodi qui sit dolore modi maxime.Sequi sunt illo fugit ea facilis voluptas ea fugit. Nesciunt voluptatem magnam cupiditate exercitationem ipsum praesentium non non. Sunt ullam voluptas et praesentium rem. Non id molestiae suscipit. Sunt voluptatum laboriosam quis et. Doloremque aliquid iusto cupiditate quo qui.",
        date: "Friday, 07 October, 2019",
        views: 127,
        id: 3,
        author: "Kali Junior Brown",
        readTime: 30,
        upVotes: 0,
        downVotes: 0,
    },
    {
        title: "Blog Post 4",
        body: "Voluptas voluptatum tempora voluptas. Blanditiis ut accusantium qui nam. Quas omnis reprehenderit quasi est. Distinctio commodi qui sit dolore modi maxime.Sequi sunt illo fugit ea facilis voluptas ea fugit. Nesciunt voluptatem magnam cupiditate exercitationem ipsum praesentium non non. Sunt ullam voluptas et praesentium rem. Non id molestiae suscipit. Sunt voluptatum laboriosam quis et. Doloremque aliquid iusto cupiditate quo qui.",
        date: "Sunday, 30 June, 2019",
        views: 512,
        id: 4,
        author: "Kali Junior Brown",
        readTime: 30,
        upVotes: 0,
        downVotes: 0,
    },
    {
        title: "Blog Post 5",
        body: "Voluptas voluptatum tempora voluptas. Blanditiis ut accusantium qui nam. Quas omnis reprehenderit quasi est. Distinctio commodi qui sit dolore modi maxime.Sequi sunt illo fugit ea facilis voluptas ea fugit. Nesciunt voluptatem magnam cupiditate exercitationem ipsum praesentium non non. Sunt ullam voluptas et praesentium rem. Non id molestiae suscipit. Sunt voluptatum laboriosam quis et. Doloremque aliquid iusto cupiditate quo qui.",
        date: "Tuesday, 22 March, 2019",
        views: 102,
        id: 5
    }
]

export const relatedPost = [
    {
        title: "Related 1",
        content: "Voluptas voluptatum tempora voluptas. Blanditiis ut accusantium qui nam. Quas omnis reprehenderit quasi est. Distinctio commodi qui sit dolore modi maxime.Sequi sunt illo fugit ea facilis voluptas ea fugit. Nesciunt voluptatem magnam cupiditate exercitationem ipsum praesentium non non. Sunt ullam voluptas et praesentium rem. Non id molestiae suscipit. Sunt voluptatum laboriosam quis et. Doloremque aliquid iusto cupiditate quo qui.",
        date: "Sunday, 30 June, 2019",
        views: 512,
        id: 1,
        author: "Kali Junior Brown",
        readTime: 30,
        upVotes: 0,
        downVotes: 0,
    },
    {
        title: "Related 2",
        content: "Voluptas voluptatum tempora voluptas. Blanditiis ut accusantium qui nam. Quas omnis reprehenderit quasi est. Distinctio commodi qui sit dolore modi maxime.Sequi sunt illo fugit ea facilis voluptas ea fugit. Nesciunt voluptatem magnam cupiditate exercitationem ipsum praesentium non non. Sunt ullam voluptas et praesentium rem. Non id molestiae suscipit. Sunt voluptatum laboriosam quis et. Doloremque aliquid iusto cupiditate quo qui.",
        date: "Tuesday, 22 March, 2019",
        views: 102,
        id: 2,
        author: "Kali Junior Brown",
        readTime: 30,
        upVotes: 0,
        downVotes: 0,
    },
    {
        title: "Related 3",
        content: "Voluptas voluptatum tempora voluptas. Blanditiis ut accusantium qui nam. Quas omnis reprehenderit quasi est. Distinctio commodi qui sit dolore modi maxime.Sequi sunt illo fugit ea facilis voluptas ea fugit. Nesciunt voluptatem magnam cupiditate exercitationem ipsum praesentium non non. Sunt ullam voluptas et praesentium rem. Non id molestiae suscipit. Sunt voluptatum laboriosam quis et. Doloremque aliquid iusto cupiditate quo qui.",
        date: "Tuesday, 22 March, 2019",
        views: 102,
        id: 3,
        author: "Kali Junior Brown",
        readTime: 30,
        upVotes: 0,
        downVotes: 0,
    }
]